package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        for (int j = 0; j < arr.length; j++) {
            for (int i = 0; i < arr.length - (1 + j); i++) {
                if (arr[i].compareTo(arr[i + 1]) > 0) {
                    swap(arr, i, i + 1);
                }
            }
        }
        return null;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(T[] arr) {
        for (int j = 0; j < arr.length; j++) {
            int min = j;
            for (int i = j; i < arr.length; i++) {
                if (arr[i].compareTo(arr[min]) < 0) {
                    min = i;
                }
            }
            swap(arr, j, min);
        }
        return null;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(T[] arr) {
        for (int i=1; i<arr.length; i++){
            for (int j=0; j<i; j++){
                if(arr[i].compareTo(arr[j]) < 0){
                    for (int k=i; k>j; k--){
                        swap(arr, k, k-1);
                    }
                    break;
                }
            }
        }
        return null;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void mergeSort(T[] arr) {
        if (arr.length <= 1 ) return; // base case
        int mid = arr.length / 2;
        T[] left = Arrays.copyOfRange(arr, 0, mid);
        T[] right = Arrays.copyOfRange(arr, mid, arr.length);

        mergeSort(left);
        mergeSort(right);
        merge(left, right, arr);
    }

     /**
     * 
     * @param left a list of type T representing the left half of arr
     * @param right a list of type T representing the right half of arr
     * @param arr a list that holds all elements in left and right 
     */
    public static <T extends Comparable<? super T>> void merge(T[] left, T[] right, T[] arr){
        int i=0, l=0, r=0;

        while(i < arr.length){
            if (l >= left.length){
                arr[i] = right[r];
                r++; 
                i++;
            } else if (r >= right.length){
                arr[i] = left[l];
                l++;
                i++;
            } else {
                if (left[l].compareTo(right[r]) < 0){
                    arr[i] = left[l];
                    i++;
                    l++;
                } else {
                    arr[i] = right[r];
                    r++;
                    i++;
                }
            }
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void quickSort(T[] arr) {
        if (arr.length <= 1) return;
        quickSort(arr, 0, arr.length-1);
    }

    /**
     * @param arr an array of type T to sort
     * @param start beginning of sorting section
     * @param end end of sorting section
     */
    public static <T extends Comparable<? super T>> void quickSort(T[] arr, int start, int end) {
        if (start >= end) return;
        int i = start;
        int j = start;
        T pivot = arr[end];
        while (j < end){
            if (arr[j].compareTo(pivot) < 0){
                swap(arr, i, j);
                i++;
            }
            j++;
        }
        swap(arr, i, end);
        
        quickSort(arr, start, i-1);
        quickSort(arr, i+1, end);
    }

    /**
     * sorts the array with heap sort algorithim
     */
    public static <T extends Comparable<? super T>> void heapSort (T[] arr) {
        int n = arr.length;
        // build max heap
        for (int i = n-1; i >= 0; i--){
            heapify(arr, i, n);
        }
        // heap sort
        while (n > 0) {
            // swap
            swap(arr, 0, n-1);
            // reduce size
            n--;
            heapify(arr, 0, n);
        }
    }

    /**
     * function to heapify a tree
     * @param arr array to heapify
     * @param root value of heap to start heapify at
     * @param n size of heap
     */
    public static <T extends Comparable<? super T>> void heapify (T[] arr, int root, int n){
        int left = root*2 + 1;
        int right = root*2 + 2;
        int max = root;

        // is root less than left child
        if (left < n && arr[root].compareTo(arr[left]) < 0){
            max = left;
        }

        // is right the largest
        if (right < n && arr[right].compareTo(arr[max]) > 0){
            max = right;
        }

        // swap and recurse
       if (arr[max].compareTo(arr[root]) != 0){
            swap(arr, root, max);
            heapify(arr, max, n);
       }
    }
}
